### ISSUE TITLE
Disable realtimeIndexing

### ISSUE THREAD

**Issue by paavo** [Flowpack/Flowpack.ElasticSearch#94]
I thought, if i **disable realtimeIndexing** in `Flowpack.ElasticSearch` **nothing should be indexed** while publishing a change. 
But i get an Error while publishing a content-change: Elastic-Server can't be reached. 

How do i disable ElasticSearch Indexing on my local environment without a ES-Server?

```
Flowpack:
  ElasticSearch:
    realtimeIndexing:
      enabled: false
```

Im using `Flowpack.ElasticSearch.ContentRepositoryAdaptor` but i didn't found any option there. 

Neos: 5.3
"flowpack/elasticsearch-contentrepositoryadaptor": "^7",
